# permissions for end users to view ecsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecsconfig-viewer-role
rules:
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - ecsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - ecsconfigs/status
  verbs:
  - get
