# permissions for end users to edit ecsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecsconfig-editor-role
rules:
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - ecsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - ecsconfigs/status
  verbs:
  - get
