---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - targetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - targetgroups/finalizers
  verbs:
  - update
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - targetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - taskdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - taskdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - ecs-deployment-manager.naffets.eu
  resources:
  - taskdefinitions/status
  verbs:
  - get
  - patch
  - update
